/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minimalui.mainFrame;

import javax.swing.JLabel;

/**
 *
 * @author Fau
 */
public class TopMenu extends javax.swing.JPanel {

    /**
     * Creates new form TopMenu
     */
    public TopMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choise1 = new javax.swing.JLabel();
        choise2 = new javax.swing.JLabel();
        choise3 = new javax.swing.JLabel();
        choise4 = new javax.swing.JLabel();
        choise5 = new javax.swing.JLabel();
        choise6 = new javax.swing.JLabel();
        choise7 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 204, 0));
        setName("menu"); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(600, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        choise1.setFont(getFont());
        choise1.setForeground(getForeground());
        choise1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choise1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuIcon.png"))); // NOI18N
        choise1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuSel.png"))); // NOI18N
        choise1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        choise1.setName("menu1"); // NOI18N
        choise1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        choise1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choise1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                choise1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                choise1MouseExited(evt);
            }
        });
        add(choise1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        choise2.setFont(getFont());
        choise2.setForeground(getForeground());
        choise2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choise2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuIcon.png"))); // NOI18N
        choise2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuSel.png"))); // NOI18N
        choise2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        choise2.setName("menu2"); // NOI18N
        choise2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        choise2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choise1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                choise2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                choise2MouseExited(evt);
            }
        });
        add(choise2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        choise3.setFont(getFont());
        choise3.setForeground(getForeground());
        choise3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choise3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuIcon.png"))); // NOI18N
        choise3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuSel.png"))); // NOI18N
        choise3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        choise3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        choise3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choise1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                choise3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                choise3MouseExited(evt);
            }
        });
        add(choise3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        choise4.setFont(getFont());
        choise4.setForeground(getForeground());
        choise4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choise4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuIcon.png"))); // NOI18N
        choise4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuSel.png"))); // NOI18N
        choise4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        choise4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        choise4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choise1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                choise4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                choise4MouseExited(evt);
            }
        });
        add(choise4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        choise5.setFont(getFont());
        choise5.setForeground(getForeground());
        choise5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choise5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuIcon.png"))); // NOI18N
        choise5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuSel.png"))); // NOI18N
        choise5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        choise5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        choise5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choise1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                choise5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                choise5MouseExited(evt);
            }
        });
        add(choise5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        choise6.setFont(getFont());
        choise6.setForeground(getForeground());
        choise6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choise6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuIcon.png"))); // NOI18N
        choise6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuSel.png"))); // NOI18N
        choise6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        choise6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        choise6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choise1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                choise6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                choise6MouseExited(evt);
            }
        });
        add(choise6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        choise7.setFont(getFont());
        choise7.setForeground(getForeground());
        choise7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        choise7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuIcon.png"))); // NOI18N
        choise7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuSel.png"))); // NOI18N
        choise7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        choise7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        choise7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choise1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                choise7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                choise7MouseExited(evt);
            }
        });
        add(choise7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void choise1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise1MouseEntered
        // TODO add your handling code here:
        JLabel choise = (JLabel)evt.getComponent();
        choise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuTravelSel.png")));
        choise.setText("DEPARTURE");
    }//GEN-LAST:event_choise1MouseEntered

    private void choise1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise1MouseExited
        // TODO add your handling code here:
        JLabel choise = (JLabel)evt.getComponent();
        choise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuIcon.png")));
        choise.setText("");
    }//GEN-LAST:event_choise1MouseExited

    private void choise2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise2MouseEntered
        // TODO add your handling code here:
        JLabel choise = (JLabel)evt.getComponent();
        choise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuPlaceSel.png")));
        choise.setText("VIAGGI");
    }//GEN-LAST:event_choise2MouseEntered

    private void choise2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise2MouseExited
        // TODO add your handling code here:
        JLabel choise = (JLabel)evt.getComponent();
        choise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuIcon.png")));
        choise.setText("");
    }//GEN-LAST:event_choise2MouseExited

    private void choise3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise3MouseEntered
        // TODO add your handling code here:
        JLabel choise = (JLabel)evt.getComponent();
        choise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuSel.png")));
        choise.setText("DESTINAZIONI");
    }//GEN-LAST:event_choise3MouseEntered

    private void choise3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise3MouseExited
        // TODO add your handling code here:
        JLabel choise = (JLabel)evt.getComponent();
        choise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuIcon.png")));
        choise.setText("");
    }//GEN-LAST:event_choise3MouseExited

    private void choise4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise4MouseEntered
        // TODO add your handling code here:
        JLabel choise = (JLabel)evt.getComponent();
        choise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuSel.png")));
        choise.setText("FLOTTA");
    }//GEN-LAST:event_choise4MouseEntered

    private void choise4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise4MouseExited
        // TODO add your handling code here:
        JLabel choise = (JLabel)evt.getComponent();
        choise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuIcon.png")));
        choise.setText("");
    }//GEN-LAST:event_choise4MouseExited

    private void choise5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise5MouseEntered
        // TODO add your handling code here:
        JLabel choise = (JLabel)evt.getComponent();
        choise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuSel.png")));
        choise.setText("ORGANICO");
    }//GEN-LAST:event_choise5MouseEntered

    private void choise5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise5MouseExited
        // TODO add your handling code here:
        JLabel choise = (JLabel)evt.getComponent();
        choise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuIcon.png")));
        choise.setText("");
    }//GEN-LAST:event_choise5MouseExited

    private void choise6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise6MouseEntered
        // TODO add your handling code here:
        JLabel choise = (JLabel)evt.getComponent();
        choise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuSel.png")));
        choise.setText("SINCRONIZZA");
    }//GEN-LAST:event_choise6MouseEntered

    private void choise6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise6MouseExited
        // TODO add your handling code here:
        JLabel choise = (JLabel)evt.getComponent();
        choise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuIcon.png")));
        choise.setText("");
    }//GEN-LAST:event_choise6MouseExited

    private void choise7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise7MouseEntered
        // TODO add your handling code here:
        JLabel choise = (JLabel)evt.getComponent();
        choise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuSel.png")));
        choise.setText("SAVE & EXIT");
    }//GEN-LAST:event_choise7MouseEntered

    private void choise7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise7MouseExited
        // TODO add your handling code here:
        JLabel choise = (JLabel)evt.getComponent();
        choise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimalui/images/menuIcon.png")));
        choise.setText("");
    }//GEN-LAST:event_choise7MouseExited

    private void choise1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choise1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_choise1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel choise1;
    private javax.swing.JLabel choise2;
    private javax.swing.JLabel choise3;
    private javax.swing.JLabel choise4;
    private javax.swing.JLabel choise5;
    private javax.swing.JLabel choise6;
    private javax.swing.JLabel choise7;
    // End of variables declaration//GEN-END:variables
}
