/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minimalui;

/**
 *
 * @author Fau
 */
public class DepartureRow extends javax.swing.JPanel {

    /**
     * Creates new form departureRow
     */
    public DepartureRow() {
        initComponents();
    }
    public void setDateFrom(String text) {
        dataFromField.setText(text);
    }

    public void setDateTo(String text) {
        dataToField.setText(text);
    }
    public void setInfoProduct(String text) {
        jTextPane1.setText(text);
    }
    public void setFreePlace(String text) {
        placeField.setText(text);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataFrom = new javax.swing.JLabel();
        dataFromField = new javax.swing.JLabel();
        dataTo = new javax.swing.JLabel();
        dataToField = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        placeTitle = new javax.swing.JLabel();
        placeField = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        placeTitle1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(760, 100));

        dataFrom.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        dataFrom.setForeground(new java.awt.Color(255, 204, 0));
        dataFrom.setText("Partenza");

        dataFromField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dataFromField.setForeground(new java.awt.Color(255, 255, 255));
        dataFromField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataFromField.setText("39/20/3094");

        dataTo.setFont(dataFrom.getFont());
        dataTo.setForeground(dataFrom.getForeground());
        dataTo.setHorizontalAlignment(dataFrom.getHorizontalAlignment());
        dataTo.setText("Ritorno");
        dataTo.setVerticalAlignment(dataFrom.getVerticalAlignment());

        dataToField.setFont(dataFromField.getFont());
        dataToField.setForeground(dataFromField.getForeground());
        dataToField.setHorizontalAlignment(dataFromField.getHorizontalAlignment());
        dataToField.setText("20/20/3045");
        dataToField.setVerticalAlignment(dataFromField.getVerticalAlignment());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        placeTitle.setFont(dataFrom.getFont());
        placeTitle.setForeground(dataFrom.getForeground());
        placeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        placeTitle.setText("Posti Disponibili");
        placeTitle.setVerticalAlignment(dataFrom.getVerticalAlignment());

        placeField.setFont(dataFromField.getFont());
        placeField.setForeground(dataFromField.getForeground());
        placeField.setHorizontalAlignment(dataFromField.getHorizontalAlignment());
        placeField.setText("56");
        placeField.setVerticalAlignment(dataFromField.getVerticalAlignment());

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        placeTitle1.setFont(dataFrom.getFont());
        placeTitle1.setForeground(dataFrom.getForeground());
        placeTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        placeTitle1.setText("Info");
        placeTitle1.setVerticalAlignment(dataFrom.getVerticalAlignment());

        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(dataFromField.getForeground());
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(getBackground());
        jTextPane1.setFont(dataFromField.getFont());
        jTextPane1.setForeground(dataFromField.getForeground());
        jTextPane1.setText("Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataFromField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataTo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataToField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(placeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(placeField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(placeTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(placeTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(placeField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dataFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataFromField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataTo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataToField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(placeTitle1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataFrom;
    private javax.swing.JLabel dataFromField;
    private javax.swing.JLabel dataTo;
    private javax.swing.JLabel dataToField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel placeField;
    private javax.swing.JLabel placeTitle;
    private javax.swing.JLabel placeTitle1;
    // End of variables declaration//GEN-END:variables
}
