/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minimalui.contentPages;

import java.awt.Component;

/**
 *
 * @author Fau
 */
public class Departure extends javax.swing.JPanel {

    /**
     * Creates new form Departure
     */
    public Departure() {
        initComponents();
    }
    
    public void addRow(Component comp) {
        travelGrid.add(comp);
        travelGrid.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        travelGrid = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(800, 50), new java.awt.Dimension(800, 50), new java.awt.Dimension(800, 50));

        setBackground(new java.awt.Color(255, 0, 51));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setOpaque(false);

        travelGrid.setBackground(new java.awt.Color(51, 51, 51));
        travelGrid.setLayout(new javax.swing.BoxLayout(travelGrid, javax.swing.BoxLayout.Y_AXIS));
        travelGrid.add(filler1);

        jScrollPane1.setViewportView(travelGrid);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel travelGrid;
    // End of variables declaration//GEN-END:variables
}
